### ISSUE TITLE
graby for wallebag with custom site_config

### ISSUE THREAD

**Issue by HolgerAusB** [j0k3r/graby#304]
Is there a way of using graby for wallabag similar to Fulltest-RSS with two folders?
```
site_config/standard
site_config/custom
```
That would be very nice. Specially when I symlink these with my FTR-Installatiion on same server.

**Comment by HolgerAusB** [comment]
@j0k3r: Hi Jérémy,

I am not a developer and php isn't that easy to read. But I did a bit of fulltext search in the code. And I came to the conclusion, that there is already a mechanism, that is loading configs from more than one directory. Am I right?

`vendor/j0k3r/graby-site-config/src/Files.php` said so. But how could I use this?

If I'd be brave enough, I could try to expand the $dirs array to FTR's site_config/custom and site_config_standard

But that would be overwritten with next wallabag release. And I am not sure, what happens, if the same filename (with different content) is available in two or three paths. I hope the first one wins or the last, just need to know.

Maybe I found the config option for this in `app/config/services.yml`:

```yml
    Graby\SiteConfig\ConfigBuilder:
        arguments:
            $config: { site_config: ['/var/www/path_to/ftr/site_config/custom', '/var/www/path_to/ftr/site_config/standard'] }
```
First short tests, look good.

- Could you please confirm, that I am using it right?
- Is the path `vendor/j0k3r/graby-site-config/` added automatically?
- What is the priority, if there are same filenames with different content. Which one is used or will they merged (which order)?
- Will this service.yml probably be overwritten with a future `make update`?
